#!/bin/bash
# ============================================================
# NeuroNet Bootstrap Script
# ============================================================
#
# Two phases:
#   Phase 1 (init):  Generate passwords, create seed .env,
#                     start infrastructure containers
#   Phase 2 (vault): Initialize Vault with secrets, policies,
#                     AppRoles, and update .env with credentials
#
# Usage:
#   ./bootstrap.sh init     # Phase 1: generate .env, start infra
#   ./bootstrap.sh vault    # Phase 2: seed Vault, create AppRoles
#   ./bootstrap.sh status   # Show what's running and configured
#
# No local vault CLI needed — all commands run via docker exec.
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_DIR="$SCRIPT_DIR/deploy"
ENV_FILE="$DEPLOY_DIR/.env"
VAULT_CONTAINER="neuro-hcvault"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()    { echo -e "${GREEN}[✓]${NC} $1"; }
warn()   { echo -e "${YELLOW}[!]${NC} $1"; }
err()    { echo -e "${RED}[✗]${NC} $1"; exit 1; }
header() { echo -e "\n${CYAN}═══ $1 ═══${NC}"; }

gen_password() {
    openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c "${1:-24}"
}

gen_token() {
    openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 64
}

# Run a vault command inside the container
v() {
    docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN="$VAULT_TOKEN" \
        "$VAULT_CONTAINER" vault "$@"
}

# ============================================================
# PHASE 1: INIT
# ============================================================

phase_init() {
    header "Phase 1: Initialize Infrastructure"

    if [ -f "$ENV_FILE" ]; then
        warn "deploy/.env already exists"
        read -p "Overwrite? (y/N): " confirm
        if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
            echo "Aborting."
            exit 0
        fi
    fi

    # Generate all passwords
    local rmq_password pg_root_password pg_iam_password iam_jwt_secret iam_master_token
    rmq_password=$(gen_password 24)
    pg_root_password=$(gen_password 24)
    pg_iam_password=$(gen_password 24)
    iam_jwt_secret=$(gen_token)
    iam_master_token=$(gen_token)

    # Write seed .env
    cat > "$ENV_FILE" << ENVFILE
# ============================================================
# NeuroNet Environment — Generated by bootstrap.sh init
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ============================================================

# ── General ─────────────────────────────────────────────────
NEURO_ENVIRONMENT=development
NEUROKIT_VERSION=v0.2.0

# ── RabbitMQ ────────────────────────────────────────────────
RABBITMQ_USERNAME=neuro
RABBITMQ_PASSWORD=$rmq_password
RABBITMQ_VHOST=/neuro

# ── Postgres ────────────────────────────────────────────────
POSTGRES_PASSWORD=$pg_root_password
VAULT_IAM_DB_PASSWORD=$pg_iam_password

# ── Vault-IAM Bootstrap ────────────────────────────────────
VAULT_IAM_JWT_SECRET=$iam_jwt_secret
VAULT_IAM_MASTER_SERVICE_TOKEN=$iam_master_token

# ── AppRole Credentials (populated by: ./bootstrap.sh vault) ──
VAULT_IAM_ROLE_ID=
VAULT_IAM_SECRET_ID=
RESOLVER_ROLE_ID=
RESOLVER_SECRET_ID=
ENTRAID_CONNECTOR_ROLE_ID=
ENTRAID_CONNECTOR_SECRET_ID=
SLACK_CONNECTOR_ROLE_ID=
SLACK_CONNECTOR_SECRET_ID=
WAZUH_CONNECTOR_ROLE_ID=
WAZUH_CONNECTOR_SECRET_ID=
CLAUDE_WORKER_ROLE_ID=
CLAUDE_WORKER_SECRET_ID=

# ── EntraID Sync ────────────────────────────────────────────
ENTRAID_SYNC_ENABLED=false
ENVFILE

    log "Generated deploy/.env with random passwords"
    echo ""
    echo "  RabbitMQ password:  $rmq_password"
    echo "  Postgres root:     $pg_root_password"
    echo "  Postgres IAM user: $pg_iam_password"
    echo "  IAM JWT secret:    ${iam_jwt_secret:0:16}..."
    echo "  IAM master token:  ${iam_master_token:0:16}..."
    echo ""

    # Start infrastructure
    header "Starting Infrastructure Containers"
    cd "$DEPLOY_DIR"
    docker-compose up -d rabbitmq vault-db hcvault

    echo ""
    log "Waiting for containers to be healthy..."
    echo ""

    # Wait for each service
    local retries=30
    local i=0

    echo -n "  RabbitMQ: "
    while [ $i -lt $retries ]; do
        if docker exec neuro-rabbitmq rabbitmq-diagnostics check_port_connectivity > /dev/null 2>&1; then
            echo -e "${GREEN}ready${NC}"
            break
        fi
        echo -n "."
        sleep 2
        i=$((i + 1))
    done
    [ $i -eq $retries ] && echo -e "${RED}timeout${NC}"

    i=0
    echo -n "  Postgres:  "
    while [ $i -lt $retries ]; do
        if docker exec neuro-vault-db pg_isready -U neuro -d neuro_vault > /dev/null 2>&1; then
            echo -e "${GREEN}ready${NC}"
            break
        fi
        echo -n "."
        sleep 2
        i=$((i + 1))
    done
    [ $i -eq $retries ] && echo -e "${RED}timeout${NC}"

    i=0
    echo -n "  Vault:     "
    while [ $i -lt $retries ]; do
        if docker exec "$VAULT_CONTAINER" vault status -format=json 2>/dev/null | grep -q '"initialized":'; then
            echo -e "${GREEN}running${NC}"
            break
        fi
        echo -n "."
        sleep 2
        i=$((i + 1))
    done
    [ $i -eq $retries ] && echo -e "${RED}timeout${NC}"

    # Check if Vault needs initialization
    echo ""
    local init_status
    init_status=$(docker exec "$VAULT_CONTAINER" vault status -format=json 2>/dev/null || echo '{}')

    if echo "$init_status" | grep -q '"initialized":false'; then
        header "Vault Initialization Required"
        echo ""
        echo "  Run:"
        echo ""
        echo "    docker exec -it $VAULT_CONTAINER vault operator init"
        echo ""
        echo "  SAVE the 5 unseal keys and root token!"
        echo "  Then unseal with 3 of the 5 keys:"
        echo ""
        echo "    docker exec -it $VAULT_CONTAINER vault operator unseal"
        echo "    docker exec -it $VAULT_CONTAINER vault operator unseal"
        echo "    docker exec -it $VAULT_CONTAINER vault operator unseal"
        echo ""
        echo "  Then run Phase 2:"
        echo ""
        echo "    export VAULT_TOKEN=<root-token>"
        echo "    ./bootstrap.sh vault"
        echo ""
    elif echo "$init_status" | grep -q '"sealed":true'; then
        header "Vault Is Sealed"
        echo ""
        echo "  Unseal it:"
        echo ""
        echo "    docker exec -it $VAULT_CONTAINER vault operator unseal  # 3x"
        echo ""
        echo "  Then run Phase 2:"
        echo ""
        echo "    export VAULT_TOKEN=<root-token>"
        echo "    ./bootstrap.sh vault"
        echo ""
    else
        echo ""
        echo "  Vault appears initialized and unsealed."
        echo "  Run Phase 2:"
        echo ""
        echo "    export VAULT_TOKEN=<root-token>"
        echo "    ./bootstrap.sh vault"
        echo ""
    fi
}

# ============================================================
# PHASE 2: VAULT
# ============================================================

phase_vault() {
    header "Phase 2: Configure HashiCorp Vault"

    # Preflight
    if [ -z "${VAULT_TOKEN:-}" ]; then
        err "VAULT_TOKEN not set. Run: export VAULT_TOKEN=<root-token>"
    fi
    if [ ! -f "$ENV_FILE" ]; then
        err "deploy/.env not found. Run './bootstrap.sh init' first."
    fi

    # Test connectivity via docker exec
    docker exec "$VAULT_CONTAINER" vault status > /dev/null 2>&1 \
        || err "Vault container '$VAULT_CONTAINER' not running or not unsealed"
    v status > /dev/null 2>&1 \
        || err "Cannot authenticate to Vault. Is your VAULT_TOKEN correct?"
    log "Connected to Vault via docker exec"

    # Read existing passwords from .env
    set -a
    source "$ENV_FILE"
    set +a

    # ── Enable secrets engine ───────────────────────────────

    header "Secrets Engine"
    if v secrets list -format=json 2>/dev/null | grep -q '"neuro-secrets/"'; then
        log "KV v2 engine already enabled"
    else
        v secrets enable -path=neuro-secrets kv-v2
        log "Enabled KV v2 at neuro-secrets/"
    fi

    # ── Seed secrets ────────────────────────────────────────

    header "Seeding Secrets"

    v kv put neuro-secrets/rabbitmq \
        host="rabbitmq" \
        port="5672" \
        username="${RABBITMQ_USERNAME}" \
        password="${RABBITMQ_PASSWORD}" \
        vhost="${RABBITMQ_VHOST}"
    log "neuro-secrets/rabbitmq"

    v kv put neuro-secrets/postgres \
        host="vault-db" \
        port="5432" \
        db="neuro_vault" \
        root_user="neuro" \
        root_password="${POSTGRES_PASSWORD}" \
        iam_user="vault_iam" \
        iam_password="${VAULT_IAM_DB_PASSWORD}"
    log "neuro-secrets/postgres"

    v kv put neuro-secrets/vault-iam \
        jwt_secret="${VAULT_IAM_JWT_SECRET}" \
        master_service_token="${VAULT_IAM_MASTER_SERVICE_TOKEN}"
    log "neuro-secrets/vault-iam"

    # Anthropic
    local anthropic_key="${NEURO_ANTHROPIC_API_KEY:-PLACEHOLDER}"
    v kv put neuro-secrets/anthropic \
        api_key="$anthropic_key" \
        default_model="claude-sonnet-4-5-20250929" \
        max_tokens="4096"
    if [ "$anthropic_key" = "PLACEHOLDER" ]; then
        warn "neuro-secrets/anthropic (PLACEHOLDER — export NEURO_ANTHROPIC_API_KEY or update manually)"
    else
        log "neuro-secrets/anthropic"
    fi

    # Microsoft Graph
    local entra_tenant="${NEURO_ENTRAID_TENANT_ID:-PLACEHOLDER}"
    local entra_client="${NEURO_ENTRAID_CLIENT_ID:-PLACEHOLDER}"
    local entra_secret="${NEURO_ENTRAID_CLIENT_SECRET:-PLACEHOLDER}"
    v kv put neuro-secrets/microsoft-graph \
        tenant_id="$entra_tenant" \
        client_id="$entra_client" \
        client_secret="$entra_secret"
    if [ "$entra_tenant" = "PLACEHOLDER" ]; then
        warn "neuro-secrets/microsoft-graph (PLACEHOLDER)"
    else
        log "neuro-secrets/microsoft-graph"
    fi

    # Slack
    local slack_user="${NEURO_SLACK_USER_TOKEN:-PLACEHOLDER}"
    local slack_app="${NEURO_SLACK_APP_TOKEN:-PLACEHOLDER}"
    v kv put neuro-secrets/slack \
        user_token="$slack_user" \
        app_level_token="$slack_app"
    if [ "$slack_user" = "PLACEHOLDER" ]; then
        warn "neuro-secrets/slack (PLACEHOLDER)"
    else
        log "neuro-secrets/slack"
    fi

    # ── Policies ────────────────────────────────────────────

    header "Creating Policies"

    write_policy() {
        local name="$1"
        local hcl="$2"
        docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN="$VAULT_TOKEN" \
            "$VAULT_CONTAINER" sh -c "echo '$hcl' > /tmp/$name.hcl && vault policy write $name /tmp/$name.hcl && rm /tmp/$name.hcl"
        log "$name"
    }

    write_policy "vault-iam" \
'path "neuro-secrets/data/rabbitmq" { capabilities = ["read"] }
path "neuro-secrets/data/postgres" { capabilities = ["read"] }
path "neuro-secrets/data/vault-iam" { capabilities = ["read"] }
path "neuro-secrets/data/microsoft-graph" { capabilities = ["read"] }'

    write_policy "resolver" \
'path "neuro-secrets/data/rabbitmq" { capabilities = ["read"] }
path "neuro-secrets/data/vault-iam" { capabilities = ["read"] }'

    write_policy "connector-entraid" \
'path "neuro-secrets/data/rabbitmq" { capabilities = ["read"] }
path "neuro-secrets/data/microsoft-graph" { capabilities = ["read"] }
path "neuro-secrets/data/vault-iam" { capabilities = ["read"] }'

    write_policy "connector-slack" \
'path "neuro-secrets/data/rabbitmq" { capabilities = ["read"] }
path "neuro-secrets/data/slack" { capabilities = ["read"] }
path "neuro-secrets/data/vault-iam" { capabilities = ["read"] }'

    write_policy "connector-wazuh" \
'path "neuro-secrets/data/rabbitmq" { capabilities = ["read"] }
path "neuro-secrets/data/wazuh" { capabilities = ["read"] }
path "neuro-secrets/data/vault-iam" { capabilities = ["read"] }'

    write_policy "agent-worker-claude" \
'path "neuro-secrets/data/rabbitmq" { capabilities = ["read"] }
path "neuro-secrets/data/anthropic" { capabilities = ["read"] }
path "neuro-secrets/data/vault-iam" { capabilities = ["read"] }'

    # ── AppRoles ────────────────────────────────────────────

    header "Creating AppRoles"

    if v auth list -format=json 2>/dev/null | grep -q '"approle/"'; then
        log "AppRole auth already enabled"
    else
        v auth enable approle
        log "Enabled AppRole auth"
    fi

    declare -A ROLE_IDS
    declare -A SECRET_IDS

    create_approle() {
        local name="$1"
        local policy="$2"

        v write "auth/approle/role/$name" \
            token_policies="$policy" \
            token_ttl=1h \
            token_max_ttl=4h \
            secret_id_ttl=0 \
            secret_id_num_uses=0

        ROLE_IDS[$name]=$(v read -field=role_id "auth/approle/role/$name/role-id")
        SECRET_IDS[$name]=$(v write -field=secret_id -f "auth/approle/role/$name/secret-id")

        log "$name (role_id: ${ROLE_IDS[$name]:0:8}...)"
    }

    create_approle "vault-iam" "vault-iam"
    create_approle "resolver" "resolver"
    create_approle "connector-entraid" "connector-entraid"
    create_approle "connector-slack" "connector-slack"
    create_approle "connector-wazuh" "connector-wazuh"
    create_approle "agent-worker-claude" "agent-worker-claude"

    # ── Update .env with AppRole credentials ────────────────

    header "Updating deploy/.env"

    sed -i "s|^VAULT_IAM_ROLE_ID=.*|VAULT_IAM_ROLE_ID=${ROLE_IDS[vault-iam]}|" "$ENV_FILE"
    sed -i "s|^VAULT_IAM_SECRET_ID=.*|VAULT_IAM_SECRET_ID=${SECRET_IDS[vault-iam]}|" "$ENV_FILE"
    sed -i "s|^RESOLVER_ROLE_ID=.*|RESOLVER_ROLE_ID=${ROLE_IDS[resolver]}|" "$ENV_FILE"
    sed -i "s|^RESOLVER_SECRET_ID=.*|RESOLVER_SECRET_ID=${SECRET_IDS[resolver]}|" "$ENV_FILE"
    sed -i "s|^ENTRAID_CONNECTOR_ROLE_ID=.*|ENTRAID_CONNECTOR_ROLE_ID=${ROLE_IDS[connector-entraid]}|" "$ENV_FILE"
    sed -i "s|^ENTRAID_CONNECTOR_SECRET_ID=.*|ENTRAID_CONNECTOR_SECRET_ID=${SECRET_IDS[connector-entraid]}|" "$ENV_FILE"
    sed -i "s|^SLACK_CONNECTOR_ROLE_ID=.*|SLACK_CONNECTOR_ROLE_ID=${ROLE_IDS[connector-slack]}|" "$ENV_FILE"
    sed -i "s|^SLACK_CONNECTOR_SECRET_ID=.*|SLACK_CONNECTOR_SECRET_ID=${SECRET_IDS[connector-slack]}|" "$ENV_FILE"
    sed -i "s|^WAZUH_CONNECTOR_ROLE_ID=.*|WAZUH_CONNECTOR_ROLE_ID=${ROLE_IDS[connector-wazuh]}|" "$ENV_FILE"
    sed -i "s|^WAZUH_CONNECTOR_SECRET_ID=.*|WAZUH_CONNECTOR_SECRET_ID=${SECRET_IDS[connector-wazuh]}|" "$ENV_FILE"
    sed -i "s|^CLAUDE_WORKER_ROLE_ID=.*|CLAUDE_WORKER_ROLE_ID=${ROLE_IDS[agent-worker-claude]}|" "$ENV_FILE"
    sed -i "s|^CLAUDE_WORKER_SECRET_ID=.*|CLAUDE_WORKER_SECRET_ID=${SECRET_IDS[agent-worker-claude]}|" "$ENV_FILE"

    log "AppRole credentials written to deploy/.env"

    # ── Summary ─────────────────────────────────────────────

    header "Bootstrap Complete"
    echo ""
    echo "  Secrets in Vault:"
    echo "    neuro-secrets/rabbitmq           ✓"
    echo "    neuro-secrets/postgres           ✓"
    echo "    neuro-secrets/vault-iam          ✓"
    echo "    neuro-secrets/anthropic          $([ "$anthropic_key" = "PLACEHOLDER" ] && echo '⚠ PLACEHOLDER' || echo '✓')"
    echo "    neuro-secrets/microsoft-graph    $([ "$entra_tenant" = "PLACEHOLDER" ] && echo '⚠ PLACEHOLDER' || echo '✓')"
    echo "    neuro-secrets/slack              $([ "$slack_user" = "PLACEHOLDER" ] && echo '⚠ PLACEHOLDER' || echo '✓')"
    echo ""
    echo "  Policies: vault-iam, resolver, connector-entraid,"
    echo "            connector-slack, connector-wazuh, agent-worker-claude"
    echo ""
    echo "  AppRoles: 6 created, credentials in deploy/.env"
    echo ""
    echo "  To update placeholders later:"
    echo "    export VAULT_TOKEN=<root-token>"
    echo "    docker exec -e VAULT_TOKEN=\$VAULT_TOKEN $VAULT_CONTAINER \\"
    echo "      vault kv put neuro-secrets/anthropic api_key=\"sk-ant-...\" default_model=\"claude-sonnet-4-5-20250929\" max_tokens=\"4096\""
    echo ""
    echo "  Next: cd deploy && docker-compose up -d"
    echo ""
}

# ============================================================
# STATUS
# ============================================================

phase_status() {
    header "NeuroNet Status"

    echo ""
    echo "  Containers:"
    for c in neuro-rabbitmq neuro-vault-db neuro-hcvault neuro-vault-iam neuro-resolver neuro-connector-entraid neuro-connector-slack neuro-agent-claude; do
        local status
        status=$(docker inspect -f '{{.State.Status}}' "$c" 2>/dev/null || echo "not found")
        local health=""
        if [ "$status" = "running" ]; then
            health=$(docker inspect -f '{{.State.Health.Status}}' "$c" 2>/dev/null || echo "")
            [ -n "$health" ] && health=" ($health)"
        fi
        printf "    %-30s %s%s\n" "$c" "$status" "$health"
    done

    echo ""
    if [ -f "$ENV_FILE" ]; then
        local approle_count
        approle_count=$(grep -c "ROLE_ID=.\+" "$ENV_FILE" 2>/dev/null || echo "0")
        echo "  deploy/.env: exists ($approle_count AppRole IDs configured)"
    else
        echo "  deploy/.env: not found — run ./bootstrap.sh init"
    fi

    echo ""
    echo "  Vault:"
    docker exec "$VAULT_CONTAINER" vault status -format=json 2>/dev/null | python3 -c "
import sys,json
d=json.load(sys.stdin)
print(f'    Initialized: {d.get(\"initialized\",\"?\")}')
print(f'    Sealed:      {d.get(\"sealed\",\"?\")}')
print(f'    Version:     {d.get(\"version\",\"?\")}')
" 2>/dev/null || echo "    Container not running"
    echo ""
}

# ============================================================
# MAIN
# ============================================================

case "${1:-}" in
    init)
        phase_init
        ;;
    vault)
        phase_vault
        ;;
    status)
        phase_status
        ;;
    *)
        echo "Usage: $0 {init|vault|status}"
        echo ""
        echo "  init    Phase 1: Generate passwords, create .env, start infrastructure"
        echo "  vault   Phase 2: Seed Vault with secrets, create policies and AppRoles"
        echo "  status  Show container and configuration status"
        echo ""
        exit 1
        ;;
esac
